#!/usr/bin/env python3
"""Regenerate font/face/embedded_font.mbt from a subset TTF.

The font is a fully-instantiated (static), subset Inconsolata embedded as a
MoonBit Bytes literal so the face tests need no filesystem and stay
target-agnostic, mirroring harfbuzz.mbt's own *_gen.mbt fixtures.

Build the subset (needs fontTools) then run this:

    python -m fontTools.varLib.instancer Inconsolata-Regular.ttf \
        wght=400 wdth=100 -o full.ttf
    python -m fontTools.subset full.ttf \
        --unicodes=U+0041,U+0061,U+006F,U+0065,U+0067,U+0020 \
        --output-file=subset.ttf --no-hinting --desubroutinize \
        --no-glyph-names --layout-features='' --notdef-outline \
        --recalc-bounds --drop-tables+=GSUB,GPOS,GDEF,kern,STAT,name,post,OS/2
    python gen_embedded_font.py subset.ttf > ../embedded_font.mbt
"""
import sys

data = open(sys.argv[1], "rb").read()
per_line = 24
out = []
out.append("// Generated by tools/gen_embedded_font.py — do not edit by hand.")
out.append("// A fully-instantiated, subset Inconsolata (glyphs: space A a e g o),")
out.append(f"// {len(data)} bytes, embedded so the face tests stay target-agnostic (no")
out.append("// filesystem), mirroring harfbuzz.mbt's own *_gen.mbt font fixtures.")
out.append("")
out.append("///|")
out.append("/// The embedded subset font's units-per-em (head table).")
out.append("pub let inconsolata_subset_upem : Int = 1000")
out.append("")
out.append("///|")
out.append("/// Raw bytes of the embedded subset Inconsolata font.")
chunks = []
for i in range(0, len(data), per_line):
    seg = data[i:i+per_line]
    chunks.append('  b"' + "".join(f"\\x{b:02x}" for b in seg) + '"')
out.append("pub let inconsolata_subset : Bytes = " + chunks[0].strip())
for c in chunks[1:]:
    out[-1] += " +"
    out.append(c)
out.append("")
print("\n".join(out))
