#!/usr/bin/env python3

from __future__ import annotations

import pathlib
import re


ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "upstream/ghostty/src/terminal/res/rgb.txt"
TARGET = ROOT / "src/terminal/x11_color_tables.mbt"
LINE_RE = re.compile(r"^\s*(\d+)\s+(\d+)\s+(\d+)\s+(.*?)\s*$")


def parse_entries() -> list[tuple[str, int, int, int]]:
    entries: list[tuple[str, int, int, int]] = []
    for raw_line in SOURCE.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip("\r")
        if not line:
            continue
        match = LINE_RE.match(line)
        if match is None:
            raise ValueError(f"cannot parse rgb.txt line: {raw_line!r}")
        r, g, b, name = match.groups()
        entries.append((name.lower(), int(r), int(g), int(b)))
    return entries


def render(entries: list[tuple[str, int, int, int]]) -> str:
    out: list[str] = []
    out.append("///|")
    out.append('/// Generated by `python3 tools/gen_x11_color_data.py`. Do not edit by hand.')
    out.append("let x11_color_entries : ReadOnlyArray[(String, RGB)] = [")
    for name, r, g, b in entries:
        escaped = name.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'  ("{escaped}", {{ r: {r}, g: {g}, b: {b} }}),')
    out.append("]")
    out.append("")
    return "\n".join(out)


def main() -> None:
    TARGET.write_text(render(parse_entries()), encoding="utf-8")


if __name__ == "__main__":
    main()
